name: Build and Commit Windows Installer

on:
  push:
    branches:
      - master

# Grant the Actions workflow write permission to push changes
permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Flutter App
        run: flutter build windows --release

      - name: Install Inno Setup
        run: choco install innosetup --yes
        shell: cmd

      - name: Create Installer Directory
        run: mkdir build\windows\installer
        shell: cmd

      - name: Copy Inno Setup Script
        run: copy desktop_ino_script.iss build\windows\installer\setup.iss
        shell: cmd

      - name: Create Installer
        run: |
          cd build\windows\installer
          ISCC setup.iss
        shell: cmd

      - name: Create misc folder
        run: if not exist misc mkdir misc
        shell: cmd

      - name: Move Installer to misc folder
        run: move build\windows\installer\Output\Doctor_Assistant.exe misc\Doctor_Assistant.exe
        shell: cmd

      - name: Commit Installer to Repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add misc/Doctor_Assistant.exe
          git commit -m "Add built Windows installer [skip ci]" || echo "No changes to commit"
          git push
        shell: cmd
